version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    environment:
#      RABBITMQ_DEFAULT_USER: 'rabbitmq'
#      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
      RABBITMQ_ENABLED_PLUGINS: 'rabbitmq_shovel, rabbitmq_shovel_management'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq' # Persists RabbitMQ data to a local directory
      - 'rabbitmq_log:/var/lib/rabbitmq'

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

  postgres:
#    image: postgres:16.10
    image: postgres:14.18
    restart: unless-stopped
#    container_name: postgresql-16.10
    container_name: postgresql-14.18
    environment:
      - 'POSTGRES_DB=udemi_pedidos-api'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data: